---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(viridis)
```

```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb |>
  mutate(stars = review_scores_location / 2) |>
  rename(borough = neighbourhood_group) |>
  select(borough, neighbourhood, stars, price, room_type, 
         lat, long) |>
  drop_na(stars)
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
borough_choices = 
  nyc_airbnb |>
  distinct(borough) |>
  pull(borough) 

selectInput(
  inputId = "borough_choice", 
  label = h3("Select Borough"), 
  choices = borough_choices, 
  selected = "Manhattan"
)
```


```{r}
min_price = nyc_airbnb |> pull(price) |> min()
  
sliderInput(
  inputId = "price_range", 
  label = h3("Select Price Range"), 
  min = 10, 
  max = 5000, 
  value = c(100, 400)
)
```


```{r}
room_choices = 
  nyc_airbnb |>
  distinct(room_type) |>
  pull(room_type) 

radioButtons(
  inputId = "room_choice", 
  label = h3("Select Room Type"), 
  choices = room_choices,
  selected = "Entire home/apt"
)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly(
  nyc_airbnb |>
    filter(
      borough == input[["borough_choice"]], 
      price %in% input[["price_range"]][1]:input[["price_range"]][2], 
      room_type == input[["room_choice"]]
    ) |>
    plot_ly(
      x = ~long, y = ~lat, type = "scatter", mode = "markers", 
      alpha = 0.5, 
      color = ~price)
)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly(
  nyc_airbnb |>
    filter(
      borough == input[["borough_choice"]], 
      room_type == input[["room_choice"]]
    ) |>
    count(neighbourhood) |>
    mutate(neighbourhood = fct_reorder(neighbourhood, n)) |>
    plot_ly(x = ~neighbourhood, y = ~n, type = "bar")
)
```

### Chart C

```{r}
renderPlotly(
  nyc_airbnb |>
    filter(
      borough == input[["borough_choice"]], 
      price %in% input[["price_range"]][1]:input[["price_range"]][2], 
      room_type == input[["room_choice"]]
    ) |>
    mutate(neighbourhood = fct_reorder(neighbourhood, price)) |>
    plot_ly(x = ~neighbourhood, y = ~price, type = "box")
)
```

